name: starship-devnet
version: 0.2.14

chains:
  - id: jsd
    name: custom
    numValidators: 1
    image: ghcr.io/cosmology-tech/jsd:latest@sha256:298d4b464039d8be430588960573f72a1dbdae2181cc562369952ab3ca220806
    home: /root/.jsd
    binary: jsdd
    prefix: cosmos
    denom: stake
    coins: 100000000000000stake
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmology-tech/jsd
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003
    resources:
      cpu: "0.3"
      memory: "300M"
    faucet:
      enabled: true
      type: starship
      resources:
        cpu: "0.1"
        memory: "100M"
    balances:
      - address: cosmos1e9ucjn5fjmetky5wezzcsccp7hqcwzrrhthpf5
        amount: "2000000000000stake"
      - address: cosmos10eykchznjdn8jdlwaj5v9wvlmdsp6kxx7u0hv9
        amount: "2000000000000stake"

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.1"
    memory: "100M"

images:
  imagePullPolicy: Always
