name: starship-devnet
version: 0.2.16

chains:
  - id: hyperweb
    name: hyperweb
    numValidators: 1
    image: ghcr.io/cosmology-tech/jsd:0.1.1
    coins: 100000000000000uhyper,100000000000000uweb,100000000000000uatom,100000000000000uusdc
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8000
    resources:
      cpu: "0.3"
      memory: "300M"
    faucet:
      enabled: true
      type: starship
      resources:
        cpu: "0.1"
        memory: "100M"

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.1"
    memory: "100M"

images:
  imagePullPolicy: Always
