name: starship-devnet
version: 0.2.14

chains:
  - id: hyperweb
    name: custom
    numValidators: 1
    image: ghcr.io/cosmology-tech/jsd:0.1.1
    home: /root/.jsd
    binary: jsdd
    prefix: hyper
    denom: uhyper
    coins: 100000000000000uhyper,100000000000000uweb,100000000000000uatom,100000000000000uusdc
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmology-tech/jsd
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8000
    resources:
      cpu: "0.3"
      memory: "300M"
    faucet:
      enabled: true
      type: starship
      resources:
        cpu: "0.1"
        memory: "100M"

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.1"
    memory: "100M"

images:
  imagePullPolicy: Always
