name: starship-devnet
version: 0.2.17

chains:
  - id: hyperweb
    name: hyperweb
    numValidators: 1
    image: ghcr.io/cosmology-tech/jsd:0.1.1
    coins: 100000000000000uhyper,100000000000000uweb,100000000000000uatom,100000000000000uusdc
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8000
    faucet:
      enabled: true
      type: starship

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: false
  ports:
    rest: 8080

images:
  imagePullPolicy: Always
