name: Sync Boilerplate to Create-Hyperweb-App

on:
  push:
    branches:
      - cha-sync-branch
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Boilerplate Repo
        uses: actions/checkout@v2
        with:
          repository: hyperweb-io/hyperweb-boilerplate
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT for private repo access
          fetch-depth: 0

      - name: Set Git User Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout CHA Sync Branch
        run: |
          git checkout cha-sync-branch
          git pull origin cha-sync-branch

      - name: Cherry-pick the commit
        run: |
          git checkout main
          git pull origin main
          git cherry-pick 1c4b4c1eb436d27154e983d3c761632c4b40e029 || git cherry-pick --abort

      - name: Clone Create-Hyperweb-App Repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/hyperweb-io/create-hyperweb-app.git ../create-hyperweb-app
          cd ../create-hyperweb-app
          git checkout main
          cd -

      - name: Copy and Apply Changes to Create-Hyperweb-App
        run: |
          rsync -av --exclude='.git' --exclude-from='.github/workflows/sync-boilerplate-cha.yaml' ./ ../create-hyperweb-app/templates/hyperweb/ --delete

      - name: Get Version from package.json
        id: get_version
        run: |
          if [ ! -f ../create-hyperweb-app/cha/package.json ]; then
            echo "package.json not found!"
            exit 1
          fi
          VERSION=$(jq -r .version ../create-hyperweb-app/cha/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Version in package.json
        run: |
          cd ../create-hyperweb-app
          if [ -f cha/package.json ]; then
            # Update the version in package.json (increment or set the value as needed)
            NEW_VERSION="${{ steps.get_version.outputs.version }}"
            jq ".version = \"$NEW_VERSION\"" cha/package.json > tmp.json && mv tmp.json cha/package.json
          else
            echo "package.json not found!"
            exit 1
          fi

      - name: Get Changelog File
        run: |
          if [ -f ../create-hyperweb-app/cha/CHANGELOG.md ]; then
            cp ../create-hyperweb-app/cha/CHANGELOG.md ../create-hyperweb-app/templates/hyperweb/
          else
            echo "CHANGELOG.md not found!"
          fi

      - name: Commit and Push Changes
        run: |
          cd ../create-hyperweb-app
          git add .
          if ! git diff-index --quiet HEAD; then
            NEW_BRANCH="sync/hyperweb-boilerplate-update-${{ steps.get_version.outputs.version }}-$(date +%Y%m%d%H%M)"
            git checkout -b $NEW_BRANCH
            git commit -m "Sync changes from hyperweb-boilerplate for version ${{ steps.get_version.outputs.version }}"
            git push origin $NEW_BRANCH
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT for private repo access
          repository: hyperweb-io/create-hyperweb-app
          base: main
          head: sync/hyperweb-boilerplate-update-${{ steps.get_version.outputs.version }}-$(date +%Y%m%d%H%M)
          title: "Sync boilerplate changes for version ${{ steps.get_version.outputs.version }}"
          body: |
            This PR contains the latest boilerplate changes from hyperweb-boilerplate for version ${{ steps.get_version.outputs.version }}.
            Also includes updates from the changelog file.
